name: build-page

on:
  push:
    branches:
      - master

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Build jekyll page
        uses: helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
        with:
          target_branch: "gh-pages"
