name: build-page

on:
  push:
    branches:
      - master

jobs:
  build-pages:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build jekyll page
        uses: helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
        with:
          target_branch: 'gh-pages'